### ISSUE TITLE
Issues on build the projects

### ISSUE THREAD

**Issue by eswarvenkat** [mortenpi/ebookdroid#1]
Dear friend,

```
            I have use your code to develop to read the pdf contents with some features has to add. But in your projects pointing the error on top of the project directory on eclipse. While  i does clean the projects the build error is shown as ,
```

/Users/admin/Downloads/adt-bundle-mac-x86_64-20130522/android-ndk/ndk-build: line 40: dirname: command not found    EBookDroid          C/C++ Problem

```
            I had mention the NDK directory into projects directory as well. But i don't know 
```

what's the mistaken on this. What are the things should accomplished in to this projects. Please help me to get rid of this problems.

**Comment by mortenpi** [comment]
It would seem that the issue might be with your environment, not with the code (ndk-build cant operate normally since it can't find some required stuff). I would suggest googling around with your error message. I found a few posts that might help out:
- http://stackoverflow.com/questions/11495434/dirname-command-not-found-error-when-i-run-android-project-ndk (same error, on Windows though)
- http://stackoverflow.com/questions/3469448/installing-using-the-android-ndk-in-eclipse

Note that I have not actually built the software, I just cloned the repo (thought I might hack on it at some point). Although the project has gone closed source in the mean time, maybe the original authors can help you out: https://code.google.com/p/ebookdroid/
